### ISSUE TITLE
ASR Program Crashes with [IOError -9981]

### ISSUE THREAD

**Issue by raybrshen** [raybrshen/robot_sds#1]
After the first transcription, program crashes with [IOError -9981].
Caused by PyAudio stream reading function.
Testing with sleep() between every stream.read()
- 0.1 cause error
- 0.01 works fine
  Presume multi-threading should solve the problem.

```
_Traceback (most recent call last):
  File "robot_sds/ASR/sound_recorder.py", line 78, in <module>
    data = stream.read(CHUNK)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
IOError: [Errno -9981] Input overflowed_
```

**Comment by raybrshen** [comment]
Already solved in issue #6 .
