### ISSUE TITLE
PyAudio Stream Read Function Overflow

### ISSUE THREAD

**Issue by raybrshen** [raybrshen/robot_sds#6]
As follow, when running on the lab's computer with a 1-channel usb microphone.

```
Traceback (most recent call last):
  File "/home/rayshen/Dev/robot_sds/ASR/test.py", line 48, in <module>
    data = stream.read(CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 605, in read
    return pa.read_stream(self._stream, num_frames)
IOError: [Errno Input overflowed] -9981
```

**Comment by raybrshen** [comment]
Cause: Audio stream of mic keep buffering data while the process is busy doing other processing for more than 0.1 sec, when the process get back to read data, the buffer is has overflowed.
Solution: Use stream.stop_stream() and stream.start_stream() to suspend mic from reading data and wake up until processing is done.

**Comment by raybrshen** [comment]
update: better wrap up "stream.read()" function with try/except statement to prevent crash from unsuccessful read operation.
